import localFont from 'next/font/local'
import 'src/app/globals.css'


const bitter = localFont({
  src: [
    {
      path: '../assets/fonts/Bitter-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Bitter-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-bitter'
})

const helvetica = localFont({
  src: [
    {
      path: '../assets/fonts/Helvetica-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/Helvetica-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-helvetica'
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bitter.variable} ${helvetica.variable}`}>{children}</body>
    </html>
  )
}
